version: "2"
services:
  rabbitmq:
      image : rabbitmq:3-management
      ports: 
          - "5672:5672"
          - "15672:15672"

  publisher-rmq:
      build: ./rabbitmq/Sender
      restart: on-failure
      ports:
        - "3000:3000"
      depends_on:
        - rabbitmq

  consumer-rmq:
      build: ./rabbitmq/Receiver
      restart: on-failure
      depends_on:
        - rabbitmq

  grpc-client:
      build: ./grpc/client
      restart: on-failure
      ports:
        - "8000:8000"

  grpc-server:
      build: ./grpc/server
      restart: on-failure

  server:
      build: ./server
      restart: on-failure